export const countryListAlpha2 = {
    "1": "United States of America (the)", // Also includes Canada, many Caribbean nations
    "7": "Russian Federation (the)", // Also Kazakhstan
    "20": "Egypt",
    "27": "South Africa",
    "30": "Greece",
    "31": "Netherlands (the)",
    "32": "Belgium",
    "33": "France",
    "34": "Spain",
    "36": "Hungary",
    "39": "Italy", // Also Vatican City, San Marino
    "40": "Romania",
    "41": "Switzerland",
    "43": "Austria",
    "44": "United Kingdom of Great Britain and Northern Ireland (the)",
    "45": "Denmark",
    "46": "Sweden",
    "47": "Norway", // Also Svalbard and Jan Mayen
    "48": "Poland",
    "49": "Germany",
    "51": "Peru",
    "52": "Mexico",
    "53": "Cuba",
    "54": "Argentina",
    "55": "Brazil",
    "56": "Chile",
    "57": "Colombia",
    "58": "Venezuela (Bolivarian Republic of)",
    "60": "Malaysia",
    "61": "Australia", // Also Christmas Island, Cocos Islands
    "62": "Indonesia",
    "63": "Philippines (the)",
    "64": "New Zealand",
    "65": "Singapore",
    "66": "Thailand",
    "81": "Japan",
    "82": "Korea (the Republic of)",
    "84": "Viet Nam",
    "86": "China",
    "90": "Turkey",
    "91": "India",
    "92": "Pakistan",
    "93": "Afghanistan",
    "94": "Sri Lanka",
    "95": "Myanmar",
    "98": "Iran (Islamic Republic of)",
    "212": "Morocco", // Also Western Sahara
    "213": "Algeria",
    "216": "Tunisia",
    "218": "Libya",
    "220": "Gambia (the)",
    "221": "Senegal",
    "222": "Mauritania",
    "223": "Mali",
    "224": "Guinea",
    "225": "Côte d'Ivoire",
    "226": "Burkina Faso",
    "227": "Niger (the)",
    "228": "Togo",
    "229": "Benin",
    "230": "Mauritius",
    "231": "Liberia",
    "232": "Sierra Leone",
    "233": "Ghana",
    "234": "Nigeria",
    "235": "Chad",
    "236": "Central African Republic (the)",
    "237": "Cameroon",
    "238": "Cabo Verde",
    "239": "Sao Tome and Principe",
    "240": "Equatorial Guinea",
    "241": "Gabon",
    "242": "Congo (the)",
    "243": "Congo (the Democratic Republic of the)",
    "244": "Angola",
    "245": "Guinea-Bissau",
    "246": "British Indian Ocean Territory (the)",
    "247": "Saint Helena, Ascension and Tristan da Cunha",
    "248": "Seychelles",
    "249": "Sudan (the)",
    "250": "Rwanda",
    "251": "Ethiopia",
    "252": "Somalia",
    "253": "Djibouti",
    "254": "Kenya",
    "255": "Tanzania, United Republic of",
    "256": "Uganda",
    "257": "Burundi",
    "258": "Mozambique",
    "260": "Zambia",
    "261": "Madagascar",
    "262": "Réunion", // Also Mayotte
    "263": "Zimbabwe",
    "264": "Namibia",
    "265": "Malawi",
    "266": "Lesotho",
    "267": "Botswana",
    "268": "Eswatini",
    "269": "Comoros (the)",
    "290": "Saint Helena, Ascension and Tristan da Cunha",
    "291": "Eritrea",
    "297": "Aruba",
    "298": "Faroe Islands (the)",
    "299": "Greenland",
    "350": "Gibraltar",
    "351": "Portugal",
    "352": "Luxembourg",
    "353": "Ireland",
    "354": "Iceland",
    "355": "Albania",
    "356": "Malta",
    "357": "Cyprus",
    "358": "Finland", // Also Åland Islands
    "359": "Bulgaria",
    "370": "Lithuania",
    "371": "Latvia",
    "372": "Estonia",
    "373": "Moldova (the Republic of)",
    "374": "Armenia",
    "375": "Belarus",
    "376": "Andorra",
    "377": "Monaco",
    "378": "San Marino",
    "380": "Ukraine",
    "381": "Serbia",
    "382": "Montenegro",
    "383": "Kosovo",
    "385": "Croatia",
    "386": "Slovenia",
    "387": "Bosnia and Herzegovina",
    "389": "Republic of North Macedonia",
    "420": "Czechia",
    "421": "Slovakia",
    "423": "Liechtenstein",
    "500": "Falkland Islands (the) [Malvinas]",
    "501": "Belize",
    "502": "Guatemala",
    "503": "El Salvador",
    "504": "Honduras",
    "505": "Nicaragua",
    "506": "Costa Rica",
    "507": "Panama",
    "508": "Saint Pierre and Miquelon",
    "509": "Haiti",
    "590": "Guadeloupe", // Also Saint Barthélemy, Saint Martin
    "591": "Bolivia (Plurinational State of)",
    "592": "Guyana",
    "593": "Ecuador",
    "594": "French Guiana",
    "595": "Paraguay",
    "596": "Martinique",
    "597": "Suriname",
    "598": "Uruguay",
    "599": "Curaçao", // Also Bonaire, Sint Eustatius and Saba
    "670": "Timor-Leste",
    "672": "Norfolk Island", // Also Antarctica
    "673": "Brunei Darussalam",
    "674": "Nauru",
    "675": "Papua New Guinea",
    "676": "Tonga",
    "677": "Solomon Islands",
    "678": "Vanuatu",
    "679": "Fiji",
    "680": "Palau",
    "681": "Wallis and Futuna",
    "682": "Cook Islands (the)",
    "683": "Niue",
    "684": "American Samoa",
    "685": "Samoa",
    "686": "Kiribati",
    "687": "New Caledonia",
    "688": "Tuvalu",
    "689": "French Polynesia",
    "690": "Tokelau",
    "691": "Micronesia (Federated States of)",
    "692": "Marshall Islands (the)",
    "850": "Korea (the Democratic People's Republic of)",
    "852": "Hong Kong",
    "853": "Macao",
    "855": "Cambodia",
    "856": "Lao People's Democratic Republic (the)",
    "880": "Bangladesh",
    "886": "Taiwan",
    "960": "Maldives",
    "961": "Lebanon",
    "962": "Jordan",
    "963": "Syrian Arab Republic",
    "964": "Iraq",
    "965": "Kuwait",
    "966": "Saudi Arabia",
    "967": "Yemen",
    "968": "Oman",
    "970": "Palestine, State of",
    "971": "United Arab Emirates (the)",
    "972": "Israel",
    "973": "Bahrain",
    "974": "Qatar",
    "975": "Bhutan",
    "976": "Mongolia",
    "977": "Nepal",
    "992": "Tajikistan",
    "993": "Turkmenistan",
    "994": "Azerbaijan",
    "995": "Georgia",
    "996": "Kyrgyzstan",
    "998": "Uzbekistan"
};

export const propertyTypeList = {
    '0': 'Casa',
    '1': 'Departamento',
    '2': 'Local',
    '3': 'Terreno/Campo',
    '4': 'Oficina',
    '5': 'Fábrica/Galpón',
    '6': 'Otro',
}

export const contractStatusList = {
    '0': 'Activo',
    '1': 'Suspendido',
    '2': 'Cancelado',
    '3': 'Finalizado',
    '4': 'Renovación',
}

export const contractCurrencyList = {
    '0': 'ARS',
    '1': 'USD',
}

export const contractPaymentMethodList = {
    '0': 'Transferencia',
    '1': 'Efectivo',
    '2': 'Crédito',
    '3': 'Débito',
    '4': 'Otro',
}

export const spanishLocaleText = {
    toolbarTitle: 'Seleccionar',
    okButtonLabel: 'Aceptar',
    cancelButtonLabel: 'Cancelar',
    clearButtonLabel: 'Limpiar',
    todayButtonLabel: 'Hoy',
  }

export const paymentStatusMapper = {
    '0': 'Pagado',
    '1': 'Deuda',
    '2': 'En proceso',
    '3': 'Parcial',
    '4': 'Otro',
}

export const maritalStatusMapper = {
    'S': 'Soltero/a',
    'C': 'Casado/a',
    'D': 'Divorciado/a',
    'V': 'Viudo/a'
}

export const accountTypeMapper = {
    '0': 'Persona física',
    '1': 'Persona jurídica',
}

export const workingCodeMapper = {
    '0': 'Empleado',
    '1': 'Autónomo',
}

export const bankAccountTypeMapper = {
    '0': 'Caja de ahorro',
    '1': 'Cuenta corriente'
}



export const provinces = [
    "Buenos Aires",
    "Catamarca",
    "Chaco",
    "Chubut",
    "Córdoba",
    "Corrientes",
    "Entre Ríos",
    "Paraná",
    "Formosa",
    "Jujuy",
    "La Pampa",
    "La Rioja",
    "Mendoza",
    "Misiones",
    "Neuquén",
    "Río Negro",
    "Salta",
    "San Juan",
    "San Luis",
    "Santa Cruz",
    "Santa Fe",
    "Santiago del Estero",
    "Tierra del Fuego",
    "Tucumán",
    "Ciudad Autónoma de Buenos Aires",
    'No aplica'
]

export const workingStatus = [
    'Autónomo',
    'Profesional',
    'Relación de dependencia'
]
